### ISSUE TITLE
CLI Distribution brew + linux

### ISSUE THREAD

**Issue by olirice** [supabase/dbdev#113]
Installing the author CLI currently requires a local rust toolchain.

This task is for publishing (at minimum) brew installable releases

linux + windows can wait until after LW if they're problematic since installing from source is always an option but would be great to include if its a light lift

**Comment by imor** [comment]
It is now possible to install on

* Linux using Homebrew
* Linux using dpkg
* Windows using Scoop.

Full details in the docs: https://supabase.github.io/dbdev/install/
