### ISSUE TITLE
Design a way to update the readme without having to push a new version

### ISSUE THREAD

**Issue by kiwicopple** [supabase/dbdev#122]
# Chore

## Describe the chore

I accidentally pushed a package without a readme:

https://database.dev/kiwicopple/countries

I wanted to update just the readme, so I edited the file on my computer then ran `dbdev publish --path .`

I got this back: `Nothing to publish`

This makes sense, but it could be nice to have a way to update the readme without needing to bump the version (i don't know if NPM allows this though)

**Comment by imor** [comment]
NPM or crates.io do not allow updating the README without publishing a new version:

* NPM: https://docs.npmjs.com/about-package-readme-files#updating-an-existing-package-readme-file. 
* Cargo: https://github.com/rust-lang/crates.io/issues/1750

I'd like to keep it simple like this. I'd definitely update the docs though, and improve the message `Nothing to publish` to include a hint about how to update the readme: by bumping the version.

**Comment by tiniscule** [comment]
I was in agreement with you until I just pushed a typo in a link in my README and now I'm on @kiwicopple side 😂

**Comment by imor** [comment]
What's the concern with fixing README and publishing the changes with a patch version bump? Is it that in your mental model README is thought of as something separate from a versioned release of the extension? Does it feel like too much hassle to release a new version just to fix README?

I'd let you guys go through the motions of releasing a new version with fixed README and if it still feels off, then reconsider this design.

**Comment by olirice** [comment]
+1 for deployed versions not being editable
there's not much downside to cutting a new patch version & users should be able to trust that nothing can change out from under existing releases (including docs/readme)

**Comment by kiwicopple** [comment]
I'm fine with that  - will close this. I've documented the decision here: https://github.com/supabase/dbdev/discussions/136
