### ISSUE TITLE
Install script fails on pg_tle extension

### ISSUE THREAD

**Issue by Sicria** [supabase/dbdev#156]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Running the install script for dbdev locally via `npx supabase db reset` results in an error. 

```
Resetting database...
Initialising schema...
Applying migration 00000000000000_setup_test_environment.sql...
Error: ERROR: extension "pg_tle" is not available (SQLSTATE 0A000)
At statement 2: create extension if not exists pg_tle
Try rerunning the command with --debug to troubleshoot the error.
 ELIFECYCLE  Command failed with exit code 1.
```
## To Reproduce

Create a migration using the install script and run the db reset to initialise the DB. 

## Expected behavior

It appears to work fine in the hosted version when doing `npx supabase db push`, but running it locally doesn't work for some reason.

## System information

- OS: macOS Ventura Version 13.3.1 (a)
- Version of supabase-js: 1.38.6
- Version of Node.js: 18.15.0

**Comment by imor** [comment]
Looks like the `pg_tle` extension was not available in the db. Which docker image version are you one? It works for me on `public.ecr.aws/supabase/postgres:15.1.0.117`.

**Comment by Sicria** [comment]
Looks like updating supabase to the latest version has resolved this. Thanks for your help!
