### ISSUE TITLE
How are TLE migration handled

### ISSUE THREAD

**Issue by themouette** [supabase/dbdev#158]
## Describe the problem

I would like to install a TLE into my project, but I'm wondering about the maintainability and did not find any information about how the TLE should provide update.

## Describe the improvement

It would be great to have a section about how to handle version migrations as a package maintainer as well as a user.
For sure dbdev is not responsible for the content of the packages, but providing guidelines would encourage adoption.

**Comment by imor** [comment]
We are still working on the docs for how to write upgrades but there's a lot of useful discussion about this in #164. I'm closing this ticket in favour of #164.
