### ISSUE TITLE
Naming Fail :|

### ISSUE THREAD

**Issue by MaximusMcCann** [supabase/dbdev#167]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

```
psql:_install.sql:43: ERROR:  invalid extension name: "supabase@dbdev"
DETAIL:  Extension names must only contain alphanumeric characters or valid separators.
```

## To Reproduce

Just try to run the long bootstrap script in the Readme on a new db.

## Expected behavior

It not to fail.

## Screenshots

```
psql:_install.sql:43: ERROR:  invalid extension name: "supabase@dbdev"
DETAIL:  Extension names must only contain alphanumeric characters or valid separators.
```

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by santiant** [comment]
Same here!

**Comment by imor** [comment]
The latest code in this repo is not yet deployed on database.dev. It contains changes to the names of packages from `<user>-<package>` to `<user>@<package>`. E.g. `supabase-dbdev` on database.dev is named `supabase@dbdev` in the latest commit. To avoid this, run the [installation script on the database.dev site](https://database.dev/supabase/dbdev) (scroll down to the `How to install` section).

**Comment by w3b6x9** [comment]
We've addressed this here: https://github.com/supabase/dbdev/pull/190
