### ISSUE TITLE
Typo in the installation script from README causes an error

### ISSUE THREAD

**Issue by btglr** [supabase/dbdev#176]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Running the installation script from README.md fails with an error.

```sql
ERROR: "version" is a required argument (SQLSTATE 22004)
At statement 7: create extension "supabase@dbdev"
```

The issue comes from this line: https://github.com/supabase/dbdev/blob/69dcb85811e42d3dd8f4411e71817550ff082d74/README.md?plain=1#L66
It differs from the installation script from this page https://database.dev/supabase/dbdev where `supabase@dbdev` (incorrect) becomes `supabase-dbdev` (correct)

## To Reproduce

1. Run the installation script

## Expected behavior

Installation script completes successfully.

**Comment by riderx** [comment]
The readme is for a version not released yet, use the website one instead i got the same issue

**Comment by w3b6x9** [comment]
@btglr: @riderx is correct. We just reverted it in this PR so the instruction in the README now should work: https://github.com/supabase/dbdev/pull/190.
