### ISSUE TITLE
supabase.com project cannot install database.dev

### ISSUE THREAD

**Issue by matart15** [supabase/dbdev#206]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

database.dev fails with no reason at all.
On local developent it succeeds sometimes. it fails sometimes. without changing any code. not stable at all.

```sh
ERROR: invalid extension name: "pointsource@supabase_rbac" (SQLSTATE 22023)
At statement 2: CREATE EXTENSION "pointsource@supabase_rbac" version '4.0.0'
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. create migration with this code 
    ```
    CREATE EXTENSION IF NOT EXISTS "moddatetime" WITH SCHEMA "public" version '1.0';
    SELECT dbdev.install('pointsource@supabase_rbac');
    CREATE EXTENSION "pointsource@supabase_rbac" version '4.0.0';
    ```
2. stop container + remove volume
3. start container + run migration
4. sometimes it just fails

## Expected behavior

be stable

## Screenshots

![Screenshot 2024-10-07 at 22 09 53](https://github.com/user-attachments/assets/6bd0a898-d454-4165-9a51-c982ca6f2bbf)

## System information

- OS: macOS
- Version of supabase --version: 1.200.3
- Version of Node.js: v20.12.2

**Comment by matart15** [comment]
Where does it download extension name?
Maybe let us check if endpoint is alive or not?

**Comment by matart15** [comment]
I thought it is fixed after i uplgrade local projects. But when i try to migrate to cloud this error is happening.

```
ERROR:  22023: invalid extension name: "pointsource@supabase_rbac"
DETAIL:  Extension names must only contain alphanumeric characters or valid separators.
CONTEXT:  SQL statement "SELECT pgtle.install_extension(package_name, rec_ver, rec_description, rec_sql, rec_requires)"
PL/pgSQL function dbdev.install(text,text,text) line 79 at PERFORM
```


I guess supabase.com version is old

**Comment by matart15** [comment]
I restarted my project. ( assume that upgraded my project since there is no upgrade button and doc says restart should do it )
https://supabase.com/docs/guides/platform/upgrading

**Comment by matart15** [comment]
`select  version();`

`PostgreSQL 15.1 (Ubuntu 15.1-1.pgdg20.04+1) on aarch64-unknown-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, 64-bit`

`PostgreSQL 15.1 (Ubuntu 15.1-1.pgdg20.04+1) on aarch64-unknown-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0, 64-bit`

both local and supabase.com postgre version are same

**Comment by matart15** [comment]
Looks like it does not work on old supabase projects. even I restart to update them. 

I recreated project and it is working. 😠

**Comment by imor** [comment]
@matart15 from the error message (`ERROR:  22023: invalid extension name: "pointsource@supabase_rbac"`) it looks like the difference between local and hosted could have been the `pg_tle` extension version rather than PG version. Support for the `@` character was added in one one of the newer `pg_tle` versions.

**Comment by matart15** [comment]
@imor thank you for response.

How do you update `pg_lte` extension?

I thought this script should do that 

https://supabase.github.io/dbdev/install-in-db-client/

**Comment by imor** [comment]
> How do you update pg_lte extension on old supabase.com project?

Upgrading the project should have upgraded `pg_tle`.

> I thought this script should do that. ( Which did not )

That script only updates the `supabase-dbdev` extension not `pg_tle` as it only contains a `create extension if not exists pg_tle;` command.

> chatGPT gave me this answer

ChatGPT is right. To check which version of `pg_tle` is currently installed run:

```sql
SELECT extname, extversion FROM pg_extension WHERE extname = 'pg_tle';
```

To update `pg_tle` run:

```sql
ALTER EXTENSION pg_tle UPDATE TO 'x.x.x';
```

Note that for the `alter extension` command to work, the correct version of `pg_tle` binary must also be present on the PG server. On the hosted server it might have been the case of an old `pg_tle`, but we can't confirm why it wasn't updated after an upgrade as you've recreated the project.

**Comment by matart15** [comment]
thank you

**Comment by imor** [comment]
> maybe we should add alter extension part to this script

probably not, because a) upgrading `pg_tle` is rare enough and b) it should be a controlled upgrade rather than through a script which installs `supabase-dbdev`. The `create extension if not exists pg_tle;` is included because `pg_tle` is a dependency of `supabase-dbdev`. But I see that docs maybe don't explain this relationship well enough, so I'll try to update docs to make this clear.
