### ISSUE TITLE
Low contrast for table cells in Dark Mode

### ISSUE THREAD

**Issue by zachallaun** [supabase/dbdev#47]
# Improve documentation

## Link 

* [Example (adminpack)](https://database.dev/michelp/adminpack)

## Describe the problem

When in dark mode, text in table cells has extremely low contrast.

## Describe the improvement

Text should not have extremely low contrast. 🙂 

## Additional context

![image](https://user-images.githubusercontent.com/503938/232125771-a853256b-050f-4b09-a7ba-0e434027b6ed.png)

**Comment by SyedMuzamilM** [comment]
I would like to work on this. Please assign this task to me.

**Comment by alaister** [comment]
@zachallaun, thanks for the bug report!

@SyedMuzamilM, go right ahead and submit a PR if you'd like to work on it – no need to wait to be assigned 😄

**Comment by SyedMuzamilM** [comment]
Thanks. Ok will submit a PR.
