### ISSUE TITLE
Names can be longer than "popular package" boxes allow

### ISSUE THREAD

**Issue by olirice** [supabase/dbdev#53]
Names can be longer than "popular package" boxes allow which causes the version number to push beyond the box edges

<img width="287" alt="Screenshot 2023-04-17 at 8 44 45 AM" src="https://user-images.githubusercontent.com/12958657/232502796-cc6c6e2b-a4a0-4467-9db0-45f3f4920810.png">

**Comment by SyedMuzamilM** [comment]
Should the version be on a new line if the package name is longer.

**Comment by imor** [comment]
This has been fixed and merged in https://github.com/supabase/dbdev/pull/68, so can be closed.
